// Update color inputs
const UPDATE_H_INPUT = 'UPDATE_H_INPUT'
const UPDATE_SV_INPUT = 'UPDATE_SV_INPUT'
const UPDATE_SL_INPUT = 'UPDATE_SL_INPUT'
const UPDATE_V_INPUT = 'UPDATE_V_INPUT'
const UPDATE_L_INPUT = 'UPDATE_L_INPUT'


const VALIDATE_HSX_INPUT = 'VALIDATE_HSX_INPUT'


export default {
  UPDATE_H_INPUT,
  UPDATE_L_INPUT,
  UPDATE_SV_INPUT,
  UPDATE_SL_INPUT,
  UPDATE_V_INPUT,
  VALIDATE_HSX_INPUT
}
