// Update Global Color Values
const UPDATE_R = 'UPDATE_R'
const UPDATE_G = 'UPDATE_G'
const UPDATE_B = 'UPDATE_B'
const UPDATE_A = 'UPDATE_A'
const UPDATE_HUE = 'UPDATE_HUE'
const UPDATE_SATURATION = 'UPDATE_SATURATION'
const UPDATE_VALUE = 'UPDATE_VALUE'
const UPDATE_LIGHTNESS = 'UPDATE_LIGHTNESS'

// Update color inputs
const UPDATE_R_INPUT = 'UPDATE_R_INPUT'
const UPDATE_G_INPUT = 'UPDATE_G_INPUT'
const UPDATE_B_INPUT = 'UPDATE_B_INPUT'
const UPDATE_A_INPUT = 'UPDATE_A_INPUT'
const UPDATE_H_INPUT = 'UPDATE_HUE_INPUT'
const UPDATE_S_INPUT = 'UPDATE_SATURATION_INPUT'
const UPDATE_V_INPUT = 'UPDATE_VALUE_INPUT'
const UPDATE_L_INPUT = 'UPDATE_LIGHTNESS_INPUT'

// Update Full values
const UPDATE_RGBA = 'UPDATE_RGBA'
const UPDATE_HSLA = 'UPDATE_HSLA'
const UPDATE_HSVA = 'UPDATE_HSVA'

const UPDATE_HEXA = 'UPDATE_HEXA'

const UPDATE_FORMAT = 'UPDATE_FORMAT'

export default {
  UPDATE_R,
  UPDATE_G,
  UPDATE_B,
  UPDATE_A,
  UPDATE_HUE,
  UPDATE_LIGHTNESS,
  UPDATE_SATURATION,
  UPDATE_VALUE,
  UPDATE_HEXA,
  UPDATE_FORMAT,
  UPDATE_R_INPUT,
  UPDATE_G_INPUT,
  UPDATE_B_INPUT,
  UPDATE_A_INPUT,
  UPDATE_H_INPUT,
  UPDATE_S_INPUT,
  UPDATE_V_INPUT,
  UPDATE_L_INPUT,
}
