const UPDATE_HUE_POSITION_VERTICAL = 'UPDATE_POSITION_VERTICAL';

const UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL = 'UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL';

export default {
  UPDATE_HUE_POSITION_VERTICAL,
  UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL
}
