// Update color inputs
const UPDATE_R_INPUT = 'UPDATE_R_INPUT'
const UPDATE_G_INPUT = 'UPDATE_G_INPUT'
const UPDATE_B_INPUT = 'UPDATE_B_INPUT'

const VALIDATE_RGB_INPUT = 'VALIDATE_RGB_INPUT'


export default {
  UPDATE_R_INPUT,
  UPDATE_G_INPUT,
  UPDATE_B_INPUT,
  VALIDATE_RGB_INPUT
}
