const UPDATE_COLOR_PICKER_AREA_POSITION = 'UPDATE_COLOR_PICKER_AREA_POSITION';

const UPDATE_COLORS_WITH_PICKER_AREA = 'UPDATE_COLORS_WITH_PICKER_AREA';

export default {
  UPDATE_COLOR_PICKER_AREA_POSITION,
  UPDATE_COLORS_WITH_PICKER_AREA
}
