const UPDATE_ALPHA_POSITION_VERTICAL = 'UPDATE_ALPHA_POSITION_VERTICAL';
const VALIDATE_ALPHA_VALUE_VERTICAL_SLIDER = 'VALIDATE_ALPHA_VALUE_VERTICAL_SLIDER'

export default {
  UPDATE_ALPHA_POSITION_VERTICAL,
  VALIDATE_ALPHA_VALUE_VERTICAL_SLIDER
}
