const UPDATE_ALPHA_POSITION = 'UPDATE_ALPHA_POSITION';
const VALIDATE_ALPHA_VALUE_WITH_SLIDER = 'VALIDATE_ALPHA_VALUE_WITH_SLIDER'

export default {
  UPDATE_ALPHA_POSITION,
  VALIDATE_ALPHA_VALUE_WITH_SLIDER
}
