const UPDATE_HUE_POSITION_VERTICAL_HOOKS = 'UPDATE_POSITION_VERTICAL_HOOKS';

const UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL_HOOKS = 'UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL_HOOKS';

export default {
  UPDATE_HUE_POSITION_VERTICAL_HOOKS,
  UPDATE_COLORS_WITH_HUE_SLIDER_VERTICAL_HOOKS
}
